/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found. It
 * should not be modified by hand.
 */

package com.example.myapplication;

public final class R {
  public static final class id {
    public static final int buttonClear=0x7f010000;
    public static final int buttonSave=0x7f010001;
    public static final int editTextInput=0x7f010002;
    public static final int textView=0x7f010003;
  }
  public static final class layout {
    public static final int activity_main=0x7f020000;
  }
  public static final class string {
    public static final int app_name=0x7f030000;
    public static final int btnClear=0x7f030001;
    public static final int btnSave=0x7f030002;
  }
}